import type { Metadata } from "next";
import "./globals.css";
import { NotificationProvider } from "@/utils/NotificationProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NotificationProvider>
      <html lang="en">
        <body className=" bg-blue-50">{children}</body>
      </html>
    </NotificationProvider>
  );
}
