import type { Metadata } from "next";

import "./globals.css";
import { NotificationProvider } from "@/utils/NotificationProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Layout from "@/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <NotificationProvider>
      <html lang={locale}>
        <body className=" bg-blue-50">
          <NextIntlClientProvider messages={messages}>
            <Layout>{children}</Layout>
          </NextIntlClientProvider>
        </body>
      </html>
    </NotificationProvider>
  );
}
